/* Generated By:JavaCC: Do not edit this line. JavaDBNetParserConstants.java */
package de.renew.dbnets.shadow;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface JavaDBNetParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 6;
  /** RegularExpression Id. */
  int FORMAL_COMMENT = 7;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 8;
  /** RegularExpression Id. */
  int ABSTRACT = 9;
  /** RegularExpression Id. */
  int ADD = 10;
  /** RegularExpression Id. */
  int ACTION = 11;
  /** RegularExpression Id. */
  int BOOLEAN = 12;
  /** RegularExpression Id. */
  int BREAK = 13;
  /** RegularExpression Id. */
  int BYTE = 14;
  /** RegularExpression Id. */
  int CASE = 15;
  /** RegularExpression Id. */
  int CATCH = 16;
  /** RegularExpression Id. */
  int CHAR = 17;
  /** RegularExpression Id. */
  int CLASS = 18;
  /** RegularExpression Id. */
  int CONST = 19;
  /** RegularExpression Id. */
  int CONTINUE = 20;
  /** RegularExpression Id. */
  int _DEFAULT = 21;
  /** RegularExpression Id. */
  int DBN_ACTION = 22;
  /** RegularExpression Id. */
  int DBN_DDL = 23;
  /** RegularExpression Id. */
  int DBN_QUERY = 24;
  /** RegularExpression Id. */
  int DEL = 25;
  /** RegularExpression Id. */
  int DO = 26;
  /** RegularExpression Id. */
  int DOUBLE = 27;
  /** RegularExpression Id. */
  int ELSE = 28;
  /** RegularExpression Id. */
  int EXTENDS = 29;
  /** RegularExpression Id. */
  int FALSE = 30;
  /** RegularExpression Id. */
  int FINAL = 31;
  /** RegularExpression Id. */
  int FINALLY = 32;
  /** RegularExpression Id. */
  int FLOAT = 33;
  /** RegularExpression Id. */
  int FOR = 34;
  /** RegularExpression Id. */
  int GOTO = 35;
  /** RegularExpression Id. */
  int GUARD = 36;
  /** RegularExpression Id. */
  int IF = 37;
  /** RegularExpression Id. */
  int IMPLEMENTS = 38;
  /** RegularExpression Id. */
  int IMPORT = 39;
  /** RegularExpression Id. */
  int INSTANCEOF = 40;
  /** RegularExpression Id. */
  int INT = 41;
  /** RegularExpression Id. */
  int INTERFACE = 42;
  /** RegularExpression Id. */
  int LONG = 43;
  /** RegularExpression Id. */
  int MANUAL = 44;
  /** RegularExpression Id. */
  int NATIVE = 45;
  /** RegularExpression Id. */
  int NEW = 46;
  /** RegularExpression Id. */
  int NULL = 47;
  /** RegularExpression Id. */
  int PACKAGE = 48;
  /** RegularExpression Id. */
  int PARAMS = 49;
  /** RegularExpression Id. */
  int PRIVATE = 50;
  /** RegularExpression Id. */
  int PROTECTED = 51;
  /** RegularExpression Id. */
  int PUBLIC = 52;
  /** RegularExpression Id. */
  int RETURN = 53;
  /** RegularExpression Id. */
  int SHORT = 54;
  /** RegularExpression Id. */
  int STATIC = 55;
  /** RegularExpression Id. */
  int SUPER = 56;
  /** RegularExpression Id. */
  int SWITCH = 57;
  /** RegularExpression Id. */
  int SYNCHRONIZED = 58;
  /** RegularExpression Id. */
  int THIS = 59;
  /** RegularExpression Id. */
  int THROW = 60;
  /** RegularExpression Id. */
  int THROWS = 61;
  /** RegularExpression Id. */
  int TRANSIENT = 62;
  /** RegularExpression Id. */
  int TRUE = 63;
  /** RegularExpression Id. */
  int TRY = 64;
  /** RegularExpression Id. */
  int VOID = 65;
  /** RegularExpression Id. */
  int VOLATILE = 66;
  /** RegularExpression Id. */
  int WHILE = 67;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 68;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 69;
  /** RegularExpression Id. */
  int HEX_LITERAL = 70;
  /** RegularExpression Id. */
  int OCTAL_LITERAL = 71;
  /** RegularExpression Id. */
  int FLOATING_POINT_LITERAL = 72;
  /** RegularExpression Id. */
  int EXPONENT = 73;
  /** RegularExpression Id. */
  int CHARACTER_LITERAL = 74;
  /** RegularExpression Id. */
  int STRING_LITERAL = 75;
  /** RegularExpression Id. */
  int IDENTIFIER = 76;
  /** RegularExpression Id. */
  int LETTER = 77;
  /** RegularExpression Id. */
  int DIGIT = 78;
  /** RegularExpression Id. */
  int LPAREN = 79;
  /** RegularExpression Id. */
  int RPAREN = 80;
  /** RegularExpression Id. */
  int LBRACE = 81;
  /** RegularExpression Id. */
  int RBRACE = 82;
  /** RegularExpression Id. */
  int LBRACKET = 83;
  /** RegularExpression Id. */
  int RBRACKET = 84;
  /** RegularExpression Id. */
  int SEMICOLON = 85;
  /** RegularExpression Id. */
  int COMMA = 86;
  /** RegularExpression Id. */
  int DOT = 87;
  /** RegularExpression Id. */
  int ASSIGN = 88;
  /** RegularExpression Id. */
  int AT = 89;
  /** RegularExpression Id. */
  int GT = 90;
  /** RegularExpression Id. */
  int LT = 91;
  /** RegularExpression Id. */
  int BANG = 92;
  /** RegularExpression Id. */
  int TILDE = 93;
  /** RegularExpression Id. */
  int HOOK = 94;
  /** RegularExpression Id. */
  int COLON = 95;
  /** RegularExpression Id. */
  int EQ = 96;
  /** RegularExpression Id. */
  int LE = 97;
  /** RegularExpression Id. */
  int GE = 98;
  /** RegularExpression Id. */
  int NE = 99;
  /** RegularExpression Id. */
  int SC_OR = 100;
  /** RegularExpression Id. */
  int SC_AND = 101;
  /** RegularExpression Id. */
  int INCR = 102;
  /** RegularExpression Id. */
  int DECR = 103;
  /** RegularExpression Id. */
  int PLUS = 104;
  /** RegularExpression Id. */
  int MINUS = 105;
  /** RegularExpression Id. */
  int STAR = 106;
  /** RegularExpression Id. */
  int SLASH = 107;
  /** RegularExpression Id. */
  int BIT_AND = 108;
  /** RegularExpression Id. */
  int BIT_OR = 109;
  /** RegularExpression Id. */
  int XOR = 110;
  /** RegularExpression Id. */
  int REM = 111;
  /** RegularExpression Id. */
  int LSHIFT = 112;
  /** RegularExpression Id. */
  int RSIGNEDSHIFT = 113;
  /** RegularExpression Id. */
  int RUNSIGNEDSHIFT = 114;
  /** RegularExpression Id. */
  int PLUSASSIGN = 115;
  /** RegularExpression Id. */
  int MINUSASSIGN = 116;
  /** RegularExpression Id. */
  int STARASSIGN = 117;
  /** RegularExpression Id. */
  int SLASHASSIGN = 118;
  /** RegularExpression Id. */
  int ANDASSIGN = 119;
  /** RegularExpression Id. */
  int ORASSIGN = 120;
  /** RegularExpression Id. */
  int XORASSIGN = 121;
  /** RegularExpression Id. */
  int REMASSIGN = 122;
  /** RegularExpression Id. */
  int LSHIFTASSIGN = 123;
  /** RegularExpression Id. */
  int RSIGNEDSHIFTASSIGN = 124;
  /** RegularExpression Id. */
  int RUNSIGNEDSHIFTASSIGN = 125;
  /** RegularExpression Id. */
  int OTHERCHAR = 126;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<SINGLE_LINE_COMMENT>",
    "<FORMAL_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "\"abstract\"",
    "\"add\"",
    "\"action\"",
    "\"boolean\"",
    "\"break\"",
    "\"byte\"",
    "\"case\"",
    "\"catch\"",
    "\"char\"",
    "\"class\"",
    "\"const\"",
    "\"continue\"",
    "\"default\"",
    "\"dbn_action\"",
    "\"dbn_ddl\"",
    "\"dbn_query\"",
    "\"del\"",
    "\"do\"",
    "\"double\"",
    "\"else\"",
    "\"extends\"",
    "\"false\"",
    "\"final\"",
    "\"finally\"",
    "\"float\"",
    "\"for\"",
    "\"goto\"",
    "\"guard\"",
    "\"if\"",
    "\"implements\"",
    "\"import\"",
    "\"instanceof\"",
    "\"int\"",
    "\"interface\"",
    "\"long\"",
    "\"manual\"",
    "\"native\"",
    "\"new\"",
    "\"null\"",
    "\"package\"",
    "\"params\"",
    "\"private\"",
    "\"protected\"",
    "\"public\"",
    "\"return\"",
    "\"short\"",
    "\"static\"",
    "\"super\"",
    "\"switch\"",
    "\"synchronized\"",
    "\"this\"",
    "\"throw\"",
    "\"throws\"",
    "\"transient\"",
    "\"true\"",
    "\"try\"",
    "\"void\"",
    "\"volatile\"",
    "\"while\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"=\"",
    "\"@\"",
    "\">\"",
    "\"<\"",
    "\"!\"",
    "\"~\"",
    "\"?\"",
    "\":\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"++\"",
    "\"--\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"%\"",
    "\"<<\"",
    "\">>\"",
    "\">>>\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"&=\"",
    "\"|=\"",
    "\"^=\"",
    "\"%=\"",
    "\"<<=\"",
    "\">>=\"",
    "\">>>=\"",
    "<OTHERCHAR>",
  };

}
