/* Generated By:JavaCC: Do not edit this line. FSNetParserConstants.java */
package de.renew.formalism.fs;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface FSNetParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 6;
  /** RegularExpression Id. */
  int FORMAL_COMMENT = 7;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 8;
  /** RegularExpression Id. */
  int ABSTRACT = 9;
  /** RegularExpression Id. */
  int ACTION = 10;
  /** RegularExpression Id. */
  int BOOLEAN = 11;
  /** RegularExpression Id. */
  int BREAK = 12;
  /** RegularExpression Id. */
  int BYTE = 13;
  /** RegularExpression Id. */
  int CASE = 14;
  /** RegularExpression Id. */
  int CATCH = 15;
  /** RegularExpression Id. */
  int CHAR = 16;
  /** RegularExpression Id. */
  int CLASS = 17;
  /** RegularExpression Id. */
  int CONST = 18;
  /** RegularExpression Id. */
  int CONTINUE = 19;
  /** RegularExpression Id. */
  int _DEFAULT = 20;
  /** RegularExpression Id. */
  int DO = 21;
  /** RegularExpression Id. */
  int DOUBLE = 22;
  /** RegularExpression Id. */
  int ELSE = 23;
  /** RegularExpression Id. */
  int EXTENDS = 24;
  /** RegularExpression Id. */
  int FALSE = 25;
  /** RegularExpression Id. */
  int FINAL = 26;
  /** RegularExpression Id. */
  int FINALLY = 27;
  /** RegularExpression Id. */
  int FLOAT = 28;
  /** RegularExpression Id. */
  int FOR = 29;
  /** RegularExpression Id. */
  int GOTO = 30;
  /** RegularExpression Id. */
  int GUARD = 31;
  /** RegularExpression Id. */
  int IF = 32;
  /** RegularExpression Id. */
  int IMPLEMENTS = 33;
  /** RegularExpression Id. */
  int IMPORT = 34;
  /** RegularExpression Id. */
  int INSTANCEOF = 35;
  /** RegularExpression Id. */
  int INT = 36;
  /** RegularExpression Id. */
  int INTERFACE = 37;
  /** RegularExpression Id. */
  int LONG = 38;
  /** RegularExpression Id. */
  int NATIVE = 39;
  /** RegularExpression Id. */
  int NEW = 40;
  /** RegularExpression Id. */
  int NULL = 41;
  /** RegularExpression Id. */
  int PACKAGE = 42;
  /** RegularExpression Id. */
  int PRIVATE = 43;
  /** RegularExpression Id. */
  int PROTECTED = 44;
  /** RegularExpression Id. */
  int PUBLIC = 45;
  /** RegularExpression Id. */
  int RETURN = 46;
  /** RegularExpression Id. */
  int SHORT = 47;
  /** RegularExpression Id. */
  int STATIC = 48;
  /** RegularExpression Id. */
  int SUPER = 49;
  /** RegularExpression Id. */
  int SWITCH = 50;
  /** RegularExpression Id. */
  int SYNCHRONIZED = 51;
  /** RegularExpression Id. */
  int THIS = 52;
  /** RegularExpression Id. */
  int THROW = 53;
  /** RegularExpression Id. */
  int THROWS = 54;
  /** RegularExpression Id. */
  int TRANSIENT = 55;
  /** RegularExpression Id. */
  int TRUE = 56;
  /** RegularExpression Id. */
  int TRY = 57;
  /** RegularExpression Id. */
  int VOID = 58;
  /** RegularExpression Id. */
  int VOLATILE = 59;
  /** RegularExpression Id. */
  int WHILE = 60;
  /** RegularExpression Id. */
  int ACCESS = 61;
  /** RegularExpression Id. */
  int ANY = 62;
  /** RegularExpression Id. */
  int TAG_SIGN = 63;
  /** RegularExpression Id. */
  int LOWER_RANGE_LITERAL = 64;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 65;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 66;
  /** RegularExpression Id. */
  int HEX_LITERAL = 67;
  /** RegularExpression Id. */
  int OCTAL_LITERAL = 68;
  /** RegularExpression Id. */
  int FLOATING_POINT_LITERAL = 69;
  /** RegularExpression Id. */
  int EXPONENT = 70;
  /** RegularExpression Id. */
  int CHARACTER_LITERAL = 71;
  /** RegularExpression Id. */
  int STRING_LITERAL = 72;
  /** RegularExpression Id. */
  int IDENTIFIER = 73;
  /** RegularExpression Id. */
  int TAGIDENT = 74;
  /** RegularExpression Id. */
  int LETTER = 75;
  /** RegularExpression Id. */
  int DIGIT = 76;
  /** RegularExpression Id. */
  int LPAREN = 77;
  /** RegularExpression Id. */
  int RPAREN = 78;
  /** RegularExpression Id. */
  int LBRACE = 79;
  /** RegularExpression Id. */
  int RBRACE = 80;
  /** RegularExpression Id. */
  int LBRACKET = 81;
  /** RegularExpression Id. */
  int RBRACKET = 82;
  /** RegularExpression Id. */
  int SEMICOLON = 83;
  /** RegularExpression Id. */
  int COMMA = 84;
  /** RegularExpression Id. */
  int DOT = 85;
  /** RegularExpression Id. */
  int DOTDOT = 86;
  /** RegularExpression Id. */
  int ASSIGN = 87;
  /** RegularExpression Id. */
  int GT = 88;
  /** RegularExpression Id. */
  int LT = 89;
  /** RegularExpression Id. */
  int BANG = 90;
  /** RegularExpression Id. */
  int TILDE = 91;
  /** RegularExpression Id. */
  int HOOK = 92;
  /** RegularExpression Id. */
  int COLON = 93;
  /** RegularExpression Id. */
  int EQ = 94;
  /** RegularExpression Id. */
  int LE = 95;
  /** RegularExpression Id. */
  int GE = 96;
  /** RegularExpression Id. */
  int NE = 97;
  /** RegularExpression Id. */
  int SC_OR = 98;
  /** RegularExpression Id. */
  int SC_AND = 99;
  /** RegularExpression Id. */
  int INCR = 100;
  /** RegularExpression Id. */
  int DECR = 101;
  /** RegularExpression Id. */
  int PLUS = 102;
  /** RegularExpression Id. */
  int MINUS = 103;
  /** RegularExpression Id. */
  int STAR = 104;
  /** RegularExpression Id. */
  int SLASH = 105;
  /** RegularExpression Id. */
  int BIT_AND = 106;
  /** RegularExpression Id. */
  int BIT_OR = 107;
  /** RegularExpression Id. */
  int XOR = 108;
  /** RegularExpression Id. */
  int REM = 109;
  /** RegularExpression Id. */
  int LSHIFT = 110;
  /** RegularExpression Id. */
  int RSIGNEDSHIFT = 111;
  /** RegularExpression Id. */
  int RUNSIGNEDSHIFT = 112;
  /** RegularExpression Id. */
  int PLUSASSIGN = 113;
  /** RegularExpression Id. */
  int MINUSASSIGN = 114;
  /** RegularExpression Id. */
  int STARASSIGN = 115;
  /** RegularExpression Id. */
  int SLASHASSIGN = 116;
  /** RegularExpression Id. */
  int ANDASSIGN = 117;
  /** RegularExpression Id. */
  int ORASSIGN = 118;
  /** RegularExpression Id. */
  int XORASSIGN = 119;
  /** RegularExpression Id. */
  int REMASSIGN = 120;
  /** RegularExpression Id. */
  int LSHIFTASSIGN = 121;
  /** RegularExpression Id. */
  int RSIGNEDSHIFTASSIGN = 122;
  /** RegularExpression Id. */
  int RUNSIGNEDSHIFTASSIGN = 123;
  /** RegularExpression Id. */
  int AT = 124;
  /** RegularExpression Id. */
  int OTHERCHAR = 125;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<SINGLE_LINE_COMMENT>",
    "<FORMAL_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "\"abstract\"",
    "\"action\"",
    "\"boolean\"",
    "\"break\"",
    "\"byte\"",
    "\"case\"",
    "\"catch\"",
    "\"char\"",
    "\"class\"",
    "\"const\"",
    "\"continue\"",
    "\"default\"",
    "\"do\"",
    "\"double\"",
    "\"else\"",
    "\"extends\"",
    "\"false\"",
    "\"final\"",
    "\"finally\"",
    "\"float\"",
    "\"for\"",
    "\"goto\"",
    "\"guard\"",
    "\"if\"",
    "\"implements\"",
    "\"import\"",
    "\"instanceof\"",
    "\"int\"",
    "\"interface\"",
    "\"long\"",
    "\"native\"",
    "\"new\"",
    "\"null\"",
    "\"package\"",
    "\"private\"",
    "\"protected\"",
    "\"public\"",
    "\"return\"",
    "\"short\"",
    "\"static\"",
    "\"super\"",
    "\"switch\"",
    "\"synchronized\"",
    "\"this\"",
    "\"throw\"",
    "\"throws\"",
    "\"transient\"",
    "\"true\"",
    "\"try\"",
    "\"void\"",
    "\"volatile\"",
    "\"while\"",
    "\"access\"",
    "\"Any\"",
    "\"#\"",
    "<LOWER_RANGE_LITERAL>",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "<IDENTIFIER>",
    "<TAGIDENT>",
    "<LETTER>",
    "<DIGIT>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"..\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\"!\"",
    "\"~\"",
    "\"?\"",
    "\":\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"++\"",
    "\"--\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"%\"",
    "\"<<\"",
    "\">>\"",
    "\">>>\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"&=\"",
    "\"|=\"",
    "\"^=\"",
    "\"%=\"",
    "\"<<=\"",
    "\">>=\"",
    "\">>>=\"",
    "\"@\"",
    "<OTHERCHAR>",
    "\"::\"",
  };

}
