package de.renew.xrn;

import CH.ifa.draw.DrawPlugin;

import CH.ifa.draw.io.ExportHolder;
import CH.ifa.draw.io.ImportHolder;

import de.renew.io.exportFormats.XRNExportFormat;
import de.renew.io.importFormats.OldXMLImportFormat;

import de.renew.plugin.PluginAdapter;
import de.renew.plugin.PluginException;
import de.renew.plugin.PluginProperties;

import java.net.URL;


/**
 * This is a generated file. Generated by PluginDevelopment
 * plugin (version 0.2)
 * Representative for the XRN plug-in.
 *
 * @author PluginGenerator
 */
public class XRNPlugin extends PluginAdapter {
    public XRNPlugin(URL url) throws PluginException {
        super(url);
    }

    public XRNPlugin(PluginProperties props) {
        super(props);
    }

    public void init() {
        ImportHolder importHolder = DrawPlugin.getCurrent().getImportHolder();
        importHolder.addImportFormat(new OldXMLImportFormat());
        ExportHolder exportHolder = DrawPlugin.getCurrent().getExportHolder();
        exportHolder.addExportFormat(new XRNExportFormat());

    }
}