/* Generated By:JavaCC: Do not edit this line. JavaNetParserConstants.java */
package de.renew.formalism.java;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface JavaNetParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 6;
  /** RegularExpression Id. */
  int FORMAL_COMMENT = 7;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 8;
  /** RegularExpression Id. */
  int ABSTRACT = 9;
  /** RegularExpression Id. */
  int ACTION = 10;
  /** RegularExpression Id. */
  int BOOLEAN = 11;
  /** RegularExpression Id. */
  int BREAK = 12;
  /** RegularExpression Id. */
  int BYTE = 13;
  /** RegularExpression Id. */
  int CASE = 14;
  /** RegularExpression Id. */
  int CATCH = 15;
  /** RegularExpression Id. */
  int CHAR = 16;
  /** RegularExpression Id. */
  int CLASS = 17;
  /** RegularExpression Id. */
  int CONST = 18;
  /** RegularExpression Id. */
  int CONTINUE = 19;
  /** RegularExpression Id. */
  int _DEFAULT = 20;
  /** RegularExpression Id. */
  int DO = 21;
  /** RegularExpression Id. */
  int DOUBLE = 22;
  /** RegularExpression Id. */
  int ELSE = 23;
  /** RegularExpression Id. */
  int EXTENDS = 24;
  /** RegularExpression Id. */
  int FALSE = 25;
  /** RegularExpression Id. */
  int FINAL = 26;
  /** RegularExpression Id. */
  int FINALLY = 27;
  /** RegularExpression Id. */
  int FLOAT = 28;
  /** RegularExpression Id. */
  int FOR = 29;
  /** RegularExpression Id. */
  int GOTO = 30;
  /** RegularExpression Id. */
  int GUARD = 31;
  /** RegularExpression Id. */
  int IF = 32;
  /** RegularExpression Id. */
  int IMPLEMENTS = 33;
  /** RegularExpression Id. */
  int IMPORT = 34;
  /** RegularExpression Id. */
  int INSTANCEOF = 35;
  /** RegularExpression Id. */
  int INT = 36;
  /** RegularExpression Id. */
  int INTERFACE = 37;
  /** RegularExpression Id. */
  int LONG = 38;
  /** RegularExpression Id. */
  int MANUAL = 39;
  /** RegularExpression Id. */
  int NATIVE = 40;
  /** RegularExpression Id. */
  int NEW = 41;
  /** RegularExpression Id. */
  int NULL = 42;
  /** RegularExpression Id. */
  int PACKAGE = 43;
  /** RegularExpression Id. */
  int PRIVATE = 44;
  /** RegularExpression Id. */
  int PROTECTED = 45;
  /** RegularExpression Id. */
  int PUBLIC = 46;
  /** RegularExpression Id. */
  int RETURN = 47;
  /** RegularExpression Id. */
  int SHORT = 48;
  /** RegularExpression Id. */
  int STATIC = 49;
  /** RegularExpression Id. */
  int SUPER = 50;
  /** RegularExpression Id. */
  int SWITCH = 51;
  /** RegularExpression Id. */
  int SYNCHRONIZED = 52;
  /** RegularExpression Id. */
  int THIS = 53;
  /** RegularExpression Id. */
  int THROW = 54;
  /** RegularExpression Id. */
  int THROWS = 55;
  /** RegularExpression Id. */
  int TRANSIENT = 56;
  /** RegularExpression Id. */
  int TRUE = 57;
  /** RegularExpression Id. */
  int TRY = 58;
  /** RegularExpression Id. */
  int VOID = 59;
  /** RegularExpression Id. */
  int VOLATILE = 60;
  /** RegularExpression Id. */
  int WHILE = 61;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 62;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 63;
  /** RegularExpression Id. */
  int HEX_LITERAL = 64;
  /** RegularExpression Id. */
  int OCTAL_LITERAL = 65;
  /** RegularExpression Id. */
  int FLOATING_POINT_LITERAL = 66;
  /** RegularExpression Id. */
  int EXPONENT = 67;
  /** RegularExpression Id. */
  int CHARACTER_LITERAL = 68;
  /** RegularExpression Id. */
  int STRING_LITERAL = 69;
  /** RegularExpression Id. */
  int IDENTIFIER = 70;
  /** RegularExpression Id. */
  int LETTER = 71;
  /** RegularExpression Id. */
  int DIGIT = 72;
  /** RegularExpression Id. */
  int LPAREN = 73;
  /** RegularExpression Id. */
  int RPAREN = 74;
  /** RegularExpression Id. */
  int LBRACE = 75;
  /** RegularExpression Id. */
  int RBRACE = 76;
  /** RegularExpression Id. */
  int LBRACKET = 77;
  /** RegularExpression Id. */
  int RBRACKET = 78;
  /** RegularExpression Id. */
  int SEMICOLON = 79;
  /** RegularExpression Id. */
  int COMMA = 80;
  /** RegularExpression Id. */
  int DOT = 81;
  /** RegularExpression Id. */
  int ASSIGN = 82;
  /** RegularExpression Id. */
  int AT = 83;
  /** RegularExpression Id. */
  int GT = 84;
  /** RegularExpression Id. */
  int LT = 85;
  /** RegularExpression Id. */
  int BANG = 86;
  /** RegularExpression Id. */
  int TILDE = 87;
  /** RegularExpression Id. */
  int HOOK = 88;
  /** RegularExpression Id. */
  int COLON = 89;
  /** RegularExpression Id. */
  int EQ = 90;
  /** RegularExpression Id. */
  int LE = 91;
  /** RegularExpression Id. */
  int GE = 92;
  /** RegularExpression Id. */
  int NE = 93;
  /** RegularExpression Id. */
  int SC_OR = 94;
  /** RegularExpression Id. */
  int SC_AND = 95;
  /** RegularExpression Id. */
  int INCR = 96;
  /** RegularExpression Id. */
  int DECR = 97;
  /** RegularExpression Id. */
  int PLUS = 98;
  /** RegularExpression Id. */
  int MINUS = 99;
  /** RegularExpression Id. */
  int STAR = 100;
  /** RegularExpression Id. */
  int SLASH = 101;
  /** RegularExpression Id. */
  int BIT_AND = 102;
  /** RegularExpression Id. */
  int BIT_OR = 103;
  /** RegularExpression Id. */
  int XOR = 104;
  /** RegularExpression Id. */
  int REM = 105;
  /** RegularExpression Id. */
  int LSHIFT = 106;
  /** RegularExpression Id. */
  int RSIGNEDSHIFT = 107;
  /** RegularExpression Id. */
  int RUNSIGNEDSHIFT = 108;
  /** RegularExpression Id. */
  int PLUSASSIGN = 109;
  /** RegularExpression Id. */
  int MINUSASSIGN = 110;
  /** RegularExpression Id. */
  int STARASSIGN = 111;
  /** RegularExpression Id. */
  int SLASHASSIGN = 112;
  /** RegularExpression Id. */
  int ANDASSIGN = 113;
  /** RegularExpression Id. */
  int ORASSIGN = 114;
  /** RegularExpression Id. */
  int XORASSIGN = 115;
  /** RegularExpression Id. */
  int REMASSIGN = 116;
  /** RegularExpression Id. */
  int LSHIFTASSIGN = 117;
  /** RegularExpression Id. */
  int RSIGNEDSHIFTASSIGN = 118;
  /** RegularExpression Id. */
  int RUNSIGNEDSHIFTASSIGN = 119;
  /** RegularExpression Id. */
  int OTHERCHAR = 120;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<SINGLE_LINE_COMMENT>",
    "<FORMAL_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "\"abstract\"",
    "\"action\"",
    "\"boolean\"",
    "\"break\"",
    "\"byte\"",
    "\"case\"",
    "\"catch\"",
    "\"char\"",
    "\"class\"",
    "\"const\"",
    "\"continue\"",
    "\"default\"",
    "\"do\"",
    "\"double\"",
    "\"else\"",
    "\"extends\"",
    "\"false\"",
    "\"final\"",
    "\"finally\"",
    "\"float\"",
    "\"for\"",
    "\"goto\"",
    "\"guard\"",
    "\"if\"",
    "\"implements\"",
    "\"import\"",
    "\"instanceof\"",
    "\"int\"",
    "\"interface\"",
    "\"long\"",
    "\"manual\"",
    "\"native\"",
    "\"new\"",
    "\"null\"",
    "\"package\"",
    "\"private\"",
    "\"protected\"",
    "\"public\"",
    "\"return\"",
    "\"short\"",
    "\"static\"",
    "\"super\"",
    "\"switch\"",
    "\"synchronized\"",
    "\"this\"",
    "\"throw\"",
    "\"throws\"",
    "\"transient\"",
    "\"true\"",
    "\"try\"",
    "\"void\"",
    "\"volatile\"",
    "\"while\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"=\"",
    "\"@\"",
    "\">\"",
    "\"<\"",
    "\"!\"",
    "\"~\"",
    "\"?\"",
    "\":\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"++\"",
    "\"--\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"%\"",
    "\"<<\"",
    "\">>\"",
    "\">>>\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"&=\"",
    "\"|=\"",
    "\"^=\"",
    "\"%=\"",
    "\"<<=\"",
    "\">>=\"",
    "\">>>=\"",
    "<OTHERCHAR>",
  };

}
